### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by ralgozino** [sighupio/fury-kubernetes-on-premises#3]
Repo name has a typo, "premise" should be "premises" or just "prem"

**Comment by angelbarrera92** [comment]
I bet is not as simple as rename and that's all...

**Comment by lnovara** [comment]
Mmm... If we change the repo name, GitHub should be smart enough to setup a redirect. (At least, Gitlab does...)

**Comment by ralgozino** [comment]
GitHub does redirect the old name to the new one. Renaming and closing the issue.
