### ISSUE TITLE
Deprecate node exporter role in favour of monitoring module

### ISSUE THREAD

**Issue by ralgozino** [sighupio/fury-kubernetes-on-premises#52]
This on-premises repo includes an Ansible [role for installing Node Exporter](https://github.com/sighupio/fury-kubernetes-on-premises/tree/main/roles/node_exporter), but [we already include node exporter as daemonset in the monitoring module](https://github.com/sighupio/fury-kubernetes-monitoring/tree/main/katalog/node-exporter) and we are not installing the role as part of the standard on-premises installation AFAIK.

I think we can deprecate the role in favour of the monitoring module.

**Comment by nutellinoit** [comment]
I agree
