### ISSUE TITLE
We should sync images on our own registry

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/fury-kubernetes-on-premises#56]
As per this change: https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/#why-isn-t-there-a-stable-list-of-domains-ips-why-can-t-i-restrict-image-pulls 

It is no more viable for a customer open this registry, because it's only a redirector to other backends

**Comment by ralgozino** [comment]
Just to be clear, the mentioned "images" are the ones for the Kubernets component like the API server, controller manager, etc. right?

**Comment by nutellinoit** [comment]
> Just to be clear, the mentioned "images" are the ones for the Kubernetes component like the API server, controller manager, etc. right?

Yes, also kube-proxy, and so on

**Comment by ralgozino** [comment]
closing as this has been fixed in https://github.com/sighupio/fury-distribution-container-image-sync/pull/145
