### ISSUE TITLE
Set the default value for kubernetes_version consistent with the module tag

### ISSUE THREAD

**Issue by stefanoghinelli** [sighupio/fury-kubernetes-on-premises#62]
The default value for variable `kubernetes_version` should be consistent with the module tag.

In example, tag `v1.22.13` by default has different version:

https://github.com/sighupio/fury-kubernetes-on-premises/blob/428721b6ce61764f4dd929e4521502a82c502e6f/roles/kube-node-common/defaults/main.yml#L5

https://github.com/sighupio/fury-kubernetes-on-premises/blob/428721b6ce61764f4dd929e4521502a82c502e6f/roles/kube-control-plane/defaults/main.yml#L17

**Comment by nutellinoit** [comment]
The version is now consistent, closing issue as done
